[development]
port = 8000

[global.databases]
diesel_postgres_pool = { url = "postgres://rocket:rocket@localhost/rocket" }

[global.jwt]
secret = "zRXL2u7hw84MTir+ZMjIGg=="

[global.api-key]
sync_api_key = "gzm4gHdtlX5VfwJecb1loZ7lA46Zhf8Gt4Y1z34SY3t5CRJ78kgb5A89B0JdRZek"

[global.oauth.github]
provider = "GitHub"
client_id = "03a9957abbca4bcbee47"
client_secret = "e71b332de2e3cfbf15bcf3cff3dd78cbdbccbcfa"
redirect_uri = "http://localhost:8000/services/gtm/api/oauth/github/callback"