name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    # branches: ["main"]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    env:
      CONTAINER_NAME: 'gtm-api'
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Docker pull
        run: |
          sudo docker pull ghcr.io/developest/gtm-api:latest
      - name: Stop old container
        run: |
          sudo docker stop ${{ env.CONTAINER_NAME }}
      - name: Run new container
        run: |
          sudo docker run \
            --name ${{ env.CONTAINER_NAME }} \
            --rm \
            -p 8000:8000
            -d ghcr.io/developest/gtm-api:latest
